### ISSUE TITLE
Feature: additional image axes

### ISSUE THREAD

**Issue by ctr26** [imagej/imagej2#227]
Hi all

Could we have additional image axes for imaging techniques that require multiple images for a later reconstruction. Structured illumination for instance needs multiple angles and storm requires 2000 per acquisition.

**Comment by imagejan** [comment]
An [`ImgPlus`](https://javadoc.scijava.org/ImageJ/index.html?net/imagej/ImgPlus.html) (and the underlying ImgLib2 `Img`) can have any number of axes.

The specifiable [axis types](https://javadoc.scijava.org/ImageJ/index.html?net/imagej/axis/Axes.html) are `Axes.X`, `Axes.Y`, `Axes.Z`, `Axes.TIME` and `Axes.CHANNEL`; for any other axis you can use `Axes.unknown()`.

**Comment by ctr26** [comment]
I should've been more clear. Could hyper stacks be made to take advantage of the possible additional axes?

**Comment by imagejan** [comment]
That's an [`imagej1`](https://github.com/imagej/imagej1) issue then. Currently, `ij.ImagePlus` only supports XYCZT dimensions, and I don't think there are any plans to change that (@rasband ?).

You might be able to use [BigDataViewer ](https://imagej.net/BigDataViewer)to achieve your goal, though. Best ask on the forum: https://forum.image.sc
