### ISSUE TITLE
Measuring dark brown

### ISSUE THREAD

**Issue by Biz7662** [imagej/imagej2#288]
Hi all,
First time using ImageJ.
I'm trying to measure dark-brown , white and green on a multisample .jpeg.
I've done the selection and cleared outside but now I don't know how to set the threshold for quantify each color.

Any ideas ?

Thank u

Anthony

**Comment by tinevez** [comment]
The best place to ask your question and discuss Science is this one:
https://forum.image.sc/
And I am sure you will get an answer.

**Comment by Biz7662** [comment]
Thank u !
