### ISSUE TITLE
Save as Raw Data

### ISSUE THREAD

**Issue by supercheney** [imagej/imagej2#289]
Hello, I met a problem about the raw data type. When I applied BaSiC to obtain a flat-field which ranges [0.5, 1.5] and save it as Raw data, the data can't be opened with numpy format np.float32. It's strange that there are negative values in np.float32 which is not consistent with the range in Image J. Hope you can help me solve this problem.

**Comment by ctrueden** [comment]
@supercheney Please post this issue on forum.image.sc. It would be very helpful to describe the exact steps you are doing in ImageJ (a script or macro is ideal, but just the list of commands is good too), and then the Python code you are trying to use to open the exported data.
